# Generated by Django 3.2.7 on 2021-10-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regioncode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('text', models.CharField(max_length=255)),
                ('allname', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('citycode', models.IntegerField()),
            ],
        ),
    ]
