# Generated by Django 3.2.7 on 2021-10-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncode',
            name='allname',
            field=models.CharField(max_length=2255),
        ),
    ]
