# Generated by Django 3.2.7 on 2021-10-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_regioncode_allname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regioncode',
            name='allname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regioncode',
            name='id',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='regioncode',
            name='pid',
            field=models.CharField(max_length=12),
        ),
    ]
