# Generated by Django 3.2.7 on 2021-10-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxt', '0002_alter_jj1001_c01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jj1001',
            name='c02',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c03',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c04',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c05',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c06',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c07',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c08',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c09',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c10',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c11',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c12',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c13',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c14',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c15',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c16',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c17',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c18',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c19',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c20',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c21',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c22',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c23',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c24',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c25',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c26',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c27',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c28',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c29',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c30',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c31',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c32',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='c33',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='pid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1001',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1102',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj110201',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1203',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj1304',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2017',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2105',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2106',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2107',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2108',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2109',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj2310',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3040',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3041',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3045',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3046',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3111',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3112',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3113',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3114',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3115',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3116',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3117',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3118',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3119',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3120',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3142',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3221',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3222',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3223',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3244',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3324',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3325',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3326',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3327',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3328',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3329',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3330',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3331',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3332',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3333',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3334',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3335',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3336',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3337',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3338',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3339',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3343',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj3347',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4063',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4064',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4067',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4068',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4148',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4149',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4150',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4153',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4155',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4156',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4159',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4251',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4257',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4261',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4352',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4354',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4358',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4360',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4362',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4365',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj4366',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5169',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5170',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5171',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5175',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5176',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5272',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5373',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5374',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj5377',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj6178',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj6179',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj6180',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj7181',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj7182',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj7283',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jj7284',
            name='schoolid',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tablepower',
            name='text',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
