# Generated by Django 3.2.7 on 2021-11-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxt', '0004_auto_20211031_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablepower',
            name='schooltype',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
