# Generated by Django 3.2.7 on 2021-11-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxt', '0005_alter_tablepower_schooltype'),
    ]

    operations = [
        migrations.CreateModel(
            name='title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, null=True)),
                ('level', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('tablename', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
