# Generated by Django 3.2.7 on 2021-11-05 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nbxt', '0006_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='title',
            new_name='rowtitle',
        ),
    ]
