# Generated by Django 3.2.7 on 2021-11-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nbxt', '0007_rename_title_rowtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='columntitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30, null=True)),
                ('level', models.IntegerField()),
                ('sort', models.IntegerField()),
                ('tablename', models.CharField(max_length=30, null=True)),
                ('code', models.CharField(max_length=2, null=True)),
            ],
        ),
    ]
